//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodeParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse without the grammar being generated..
        /// </summary>
        internal static string Err_CannotParseWithoutGrammar {
            get {
                return ResourceManager.GetString("Err_CannotParseWithoutGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build a grammar.
        ///{0}
        ///
        ///Language state list:
        ///{1}
        ///
        ///(Scroll up for the actual error message! :)).
        /// </summary>
        internal static string Err_FailedToBuildGrammar {
            get {
                return ResourceManager.GetString("Err_FailedToBuildGrammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the given input.
        ///{0}.
        /// </summary>
        internal static string Err_FailedToParse {
            get {
                return ResourceManager.GetString("Err_FailedToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index cannot be smaller than zero..
        /// </summary>
        internal static string Err_IndexSmallerThanZero {
            get {
                return ResourceManager.GetString("Err_IndexSmallerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot index this value with a length of {0} at index {1}..
        /// </summary>
        internal static string Err_InvalidIndex {
            get {
                return ResourceManager.GetString("Err_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple KeyTerms with the name &quot;{0}&quot; could be found: {1}(Value: {2}, Flags: {3}) and {4}(Value: {5}, Flags: {6}).
        /// </summary>
        internal static string Err_KeyTermConflict {
            get {
                return ResourceManager.GetString("Err_KeyTermConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type &quot;{0}&quot; is not a subclass of &quot;{1}&quot;..
        /// </summary>
        internal static string Err_NotSubclassOf {
            get {
                return ResourceManager.GetString("Err_NotSubclassOf", resourceCulture);
            }
        }
    }
}
