using System;
using System.Runtime.Serialization;

namespace NodeParser.Exceptions
{
    /// <summary>
    ///     This exceptions indicates an error with a grammar generated by the node parser.
    /// </summary>
    [Serializable]
    public class NodeParserGrammarException : Exception
    {
        public NodeParserGrammarException() {}
        public NodeParserGrammarException(string message) : base(message) {}
        public NodeParserGrammarException(string message, Exception inner) : base(message, inner) {}

        protected NodeParserGrammarException(
            SerializationInfo info,
            StreamingContext context) : base(info, context) {}
    }
}